"""add vote_message_id to games

Revision ID: 385ce08ec5c0
Revises: 167b606f9c3b
Create Date: 2026-03-11 21:06:23.735945

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "385ce08ec5c0"
down_revision: str | None = "167b606f9c3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games", sa.Column("vote_message_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "vote_message_id")
    # ### end Alembic commands ###
