"""add lobby_message_id to games

Revision ID: 8c0665c78dfb
Revises: 385ce08ec5c0
Create Date: 2026-03-11 21:36:19.131702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c0665c78dfb"
down_revision: str | None = "385ce08ec5c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column("lobby_message_id", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "lobby_message_id")
    # ### end Alembic commands ###
